# Notes
# Look into node_module caching between steps

name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/common.yml
        with: 
          node-version: ${{ inputs.node-version }}

      # - uses: actions/checkout@v4

      # - name: Use Node.js ${{ inputs.node-version }}
      #   uses: actions/setup-node@v4 # Maybe v4?
      #   with:
      #     node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --if-present

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts # Artifact name
          compression-level: 9 # Best compression
          path: dist/ # Path to the artifacts directory

  build-documentation-app:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts # Artifact name (must match upload name)
          path: ./dist

      # - name: Install dependencies
      #   run: npm ci

      - name: Build the project
        run: npm run build-docs --if-present

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-docs # Artifact name
          compression-level: 9 # Best compression
          path: | # Path to the artifacts directory
            docs/ 
            !**/node_modules/**/*
